package sse

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"time"

	"ella.to/sse"

	"ella.to/pipe/signal"
)

type Server struct {
	mapper    *Mapper
	connIDGen ConnIDGenerator
}

// ConnIDGenerator is a function that generates a unique connection ID based on the request context.
// The context contains information about the HTTP request, including user authentication and permissions.
// This allows tying connection IDs to user permissions and session information.
type ConnIDGenerator func(ctx context.Context, r *http.Request) (string, error)

var _ http.Handler = (*Server)(nil)

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	inbox, err := ParseRequest(r)
	if err != nil {
		http.Error(w, "Bad Request", http.StatusBadRequest)
		return
	}

	switch r.Method {
	case http.MethodGet:
		pusher, err := sse.CreateHttpPusher(w, sse.WithHttpPusherPingDuration(30*time.Second))
		if err != nil {
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
		}
		defer pusher.Close()

		msgCh := s.mapper.Subscribe(inbox.String())
		defer s.mapper.Unsubscribe(inbox.String(), msgCh)
		var msgCount int64

		for {
			select {
			case <-r.Context().Done():
				return
			case msg, ok := <-msgCh:
				if !ok {
					return
				}

				b, err := json.Marshal(msg)
				if err != nil {
					continue
				}

				err = pusher.Push(&sse.Message{
					Id:    strconv.FormatInt(msgCount, 10),
					Event: "data",
					Data:  string(b),
				})
				if err != nil {
					return
				}
				msgCount++
			}
		}

	case http.MethodPost:
		msg := &signal.Msg{}
		if err := json.NewDecoder(r.Body).Decode(msg); err != nil {
			http.Error(w, "Bad Request", http.StatusBadRequest)
			return
		}

		// If this is an initial exchange message and we have a connection ID generator,
		// generate a connection ID and send it to both the sender and recipient.
		// Only generate for main inbox to ensure each connection pair gets ONE shared ID.
		if msg.Type == signal.TypeExchange && s.connIDGen != nil && inbox.IsMain() {
			connID, err := s.connIDGen(r.Context(), r)
			if err != nil {
				http.Error(w, "Failed to generate connection ID", http.StatusInternalServerError)
				return
			}

			// The TypeExchange message body contains the sender's receiving inbox
			var senderInbox signal.Inbox
			if err := json.Unmarshal(msg.Body, &senderInbox); err == nil {
				// Send the connection ID to the sender
				connIDMsg := signal.CreateMsg(0, map[string]string{"conn_id": connID})
				_ = s.Send(r.Context(), &senderInbox, connIDMsg)
			}

			// Send the connection ID to the recipient
			connIDMsg := signal.CreateMsg(0, map[string]string{"conn_id": connID})
			if err := s.Send(r.Context(), inbox, connIDMsg); err != nil {
				http.Error(w, "Failed to send connection ID", http.StatusInternalServerError)
				return
			}
		}

		err := s.Send(r.Context(), inbox, msg)
		if err != nil {
			http.Error(w, "Failed to send message", http.StatusInternalServerError)
			return
		}

		w.WriteHeader(http.StatusAccepted)

	default:
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
	}
}

// Send can be used to send a message to the specified inbox.
// the common use case is to send a custom message to a specific inbox.
// If the method is called outside of this package, make sure the type of the message is 0.
// this method made public to allow advanced use cases, use with caution.
func (s *Server) Send(ctx context.Context, inbox *signal.Inbox, msg *signal.Msg) error {
	select {
	case s.mapper.Get(inbox.String()) <- msg:
		return nil
	default:
		return fmt.Errorf("failed to send message to inbox: %s", inbox.String())
	}
}

type ServerOption func(*Server) error

// WithConnIDGenerator sets a function that generates connection IDs based on the request context.
// This allows the server to assign connection IDs that can be tied to user permissions and sessions.
// If not set, connection IDs will be generated by the clients themselves.
func WithConnIDGenerator(gen ConnIDGenerator) ServerOption {
	return func(s *Server) error {
		if gen == nil {
			return errors.New("connection ID generator cannot be nil")
		}
		if s.connIDGen != nil {
			return errors.New("connection ID generator already set")
		}
		s.connIDGen = gen
		return nil
	}
}

func NewServer(opts ...ServerOption) (*Server, error) {
	s := &Server{
		mapper: NewMapper(),
	}

	for _, opt := range opts {
		if err := opt(s); err != nil {
			return nil, err
		}
	}

	return s, nil
}

type Client struct {
	host         string
	httpClient   *http.Client
	unknownMsgFn func(*signal.Msg)
}

type clientReceiver struct {
	receive func(ctx context.Context) (*signal.Msg, error)
	close   func() error
}

func (cr *clientReceiver) Receive(ctx context.Context) (*signal.Msg, error) {
	return cr.receive(ctx)
}

func (cr *clientReceiver) Close() error {
	if cr.close == nil {
		return nil
	}
	return cr.close()
}

var _ signal.ReceiverCloser = (*clientReceiver)(nil)

var _ signal.Signal = (*Client)(nil)

func (c *Client) Send(ctx context.Context, inbox *signal.Inbox, msg *signal.Msg) error {
	url, err := c.getURL(inbox)
	if err != nil {
		return err
	}

	b, err := json.Marshal(msg)
	if err != nil {
		return err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(b))
	if err != nil {
		return err
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return err
	}

	defer resp.Body.Close()

	if resp.StatusCode == http.StatusAccepted {
		return nil
	}

	errMsg, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	return fmt.Errorf("failed to send message, status code: %d: %s", resp.StatusCode, errMsg)
}

func (c *Client) Receiver(inbox *signal.Inbox) (signal.Receiver, error) {
	url, err := c.getURL(inbox)
	if err != nil {
		return nil, err
	}

	receiver, err := sse.CreateHttpReceiver(url, sse.WithHttpReceiverClient(c.httpClient))
	if err != nil {
		return nil, err
	}

	return &clientReceiver{
		receive: func(ctx context.Context) (*signal.Msg, error) {
			for {
				if err := ctx.Err(); err != nil {
					return nil, err
				}

				type recvResult struct {
					msg *sse.Message
					err error
				}

				resultCh := make(chan recvResult, 1)
				go func() {
					msg, err := receiver.Receive()
					resultCh <- recvResult{msg: msg, err: err}
				}()

				var msg *sse.Message
				select {
				case <-ctx.Done():
					_ = receiver.Close()
					return nil, ctx.Err()
				case result := <-resultCh:
					msg = result.msg
					err = result.err
				}

				if err != nil {
					return nil, err
				}

				// Skip non-JSON messages such as SSE keepalive pings (e.g. ": ping").
				// These are server-side heartbeats and are not valid signal messages.
				// A fresh Msg is allocated per message: the previous one may
				// still be retained by the caller.
				sigMsg := &signal.Msg{}
				if err := json.Unmarshal([]byte(msg.Data), sigMsg); err != nil {
					continue
				}

				// Type 0 messages are now passed through to the caller
				// If unknownMsgFn is set, it's called but the message is still returned
				if sigMsg.Type == 0 && c.unknownMsgFn != nil {
					c.unknownMsgFn(sigMsg)
				}

				// Return all messages including type 0
				return sigMsg, nil
			}
		},
		close: receiver.Close,
	}, nil
}

func (c *Client) getURL(inbox *signal.Inbox) (string, error) {
	u, err := url.Parse(c.host)
	if err != nil {
		return "", err
	}

	q := u.Query()
	q.Set("inbox", inbox.String())
	u.RawQuery = q.Encode()

	return u.String(), nil
}

type ClientOption func(*Client) error

// WithUnknownMessageHandler sets a handler function for unknown messages (type 0).
// This allows the client to process messages that are not handled by the default receiver.
// make sure the function processes the message quickly to avoid blocking the receiver.
func WithUnknownMessageHandler(fn func(*signal.Msg)) ClientOption {
	return func(c *Client) error {
		c.unknownMsgFn = fn
		return nil
	}
}

func WithHttpClient(httpClient *http.Client) ClientOption {
	return func(c *Client) error {
		if httpClient == nil {
			return errors.New("http client cannot be nil")
		}

		if c.httpClient != nil {
			return errors.New("http client already set")
		}

		c.httpClient = httpClient
		return nil
	}
}

func NewClient(host string, opts ...ClientOption) (*Client, error) {
	client := &Client{
		host: host,
	}

	for _, opt := range opts {
		if err := opt(client); err != nil {
			return nil, err
		}
	}

	if client.httpClient == nil {
		client.httpClient = &http.Client{
			Transport: http.DefaultTransport,
		}
	}

	return client, nil
}

func ParseRequest(r *http.Request) (*signal.Inbox, error) {
	if r.Method != http.MethodGet && r.Method != http.MethodPost {
		return nil, fmt.Errorf("invalid method: %s", r.Method)
	}

	return signal.ParseInbox(r.URL.Query().Get("inbox"))
}
